[[language]]
name = "python"
scope = "source.python"
auto-format = true
rulers = [80]
indent = { tab-width = 4, unit = " " }
# formatter = { command = "black", args = ["-", "-q"] }
roots = ["pyproject.toml", "pyrightconfig.json", "Poetry.lock"]
language-servers = [{ name = "pyright" }, { name = "ruff-lsp" }]
[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]
config = { python = { analysis = { autoSearchPaths = true, useLibraryCodeForTypes = true, diagnosticMode = "openFilesOnly", autoImportCompletions = false } } }
[language-server.ruff-lsp]
command = "ruff-lsp"
# TODO: use pylyzer when nixpkgs.pylyzer is fixed
[language-server.pylyzer]
command = "pylyzer"
args = ["--server"]

[[language]]
name = "nix"
# NOTE: nixd formatting (with nix fmt) deletes malformed nix files. keep auto-format off until fixed or workaround is found. for now make sure flake.nix has inputs, outputs, and description before formatting
auto-format = false
roots = [".nixd.json", "flake.nix", ".git"]
language-servers = [{ name = "nixd" }]
# [language-server.nil]
# config = { nil = { formatting = { command = ["alejandra", "-q"] } } }
[language-server.nixd]
command = "nixd"
config = { nixd = { formatting = { command = "nix fmt -- -" } } }
# config = { nixd = { formatting = { command = "treefmt --stdin {file}" } } } # TODO: not sure if this will work
[[language]]
name = "toml"
auto-format = true
