local icons = require("utils.icons")
return {
    {
        "nvim-tree/nvim-web-devicons",
        lazy = true,
        opts = {
            override = {
                default_icon = {
                    color = "#7c888c",
                    cterm_color = "66",
                    icon = vim.trim(icons.kinds.File),
                    name = "Default",
                },
                desktop = {
                    color = "#997bca",
                    cterm_color = "60",
                    icon = vim.trim(icons.ft.Desktop),
                    name = "DesktopEntry",
                },
                lock = {
                    color = "#bbbbbb",
                    cterm_color = "250",
                    icon = vim.trim(icons.ft.Lock),
                    name = "Lock",
                },
                git = {
                    color = "#e84d31",
                    cterm_color = "196",
                    icon = vim.trim(icons.ft.Git),
                    name = "GitLogo",
                },
                commit_editmsg = {
                    color = "#e84d31",
                    cterm_color = "239",
                    icon = vim.trim(icons.ft.Git),
                    name = "GitCommit",
                },
                env = { color = "#d0bf41", icon = vim.trim(icons.ft.Env), name = "Env" },
            },
            override_by_extension = {
                asm = {
                    color = "#d65050",
                    cterm_color = "167",
                    icon = vim.trim(icons.ft.Assembly),
                    name = "Assembly",
                },
                s = {
                    color = "#d65050",
                    cterm_color = "167",
                    icon = vim.trim(icons.ft.Assembly),
                    name = "S",
                },
                o = {
                    color = "#88a0a7",
                    cterm_color = "66",
                    icon = vim.trim(icons.ft.Object),
                    name = "O",
                },
                bak = {
                    color = "#6d8086",
                    cterm_color = "66",
                    icon = vim.trim(icons.ft.Bak),
                    name = "Bak",
                },
                cu = {
                    color = "#76b900",
                    cterm_color = "2",
                    icon = vim.trim(icons.ft.Cuda),
                    name = "Cuda",
                },
                epub = {
                    color = "#b30b00",
                    cterm_color = "124",
                    icon = vim.trim(icons.ft.Epub),
                    name = "Epub",
                },
                raw = {
                    color = "#ff9800",
                    cterm_color = "208",
                    icon = vim.trim(icons.ft.Raw),
                    name = "Raw",
                },
                dat = {
                    color = "#6dcde8",
                    cterm_color = "81",
                    icon = vim.trim(icons.ft.Data),
                    name = "Data",
                },
                pickle = {
                    color = "#ffbc03",
                    cterm_color = "214",
                    icon = vim.trim(icons.ft.Data),
                    name = "Pickle",
                },
                el = {
                    color = "#a374ea",
                    cterm_color = "61",
                    icon = vim.trim(icons.ft.Elisp),
                    name = "Elisp",
                },
                patch = {
                    color = "#e84d31",
                    cterm_color = "166",
                    icon = vim.trim(icons.ft.Git),
                    name = "Patch",
                },
                md = {
                    color = "#6fb5ca",
                    cterm_color = "74",
                    icon = vim.trim(icons.ft.Markdown),
                    name = "Md",
                },
                mdx = {
                    color = "#6fb5ca",
                    cterm_color = "74",
                    icon = vim.trim(icons.ft.Markdown),
                    name = "Mdx",
                },
                markdown = {
                    color = "#6fb5ca",
                    cterm_color = "74",
                    icon = vim.trim(icons.ft.Markdown),
                    name = "Markdown",
                },
                rmd = {
                    color = "#6fb5ca",
                    cterm_color = "74",
                    icon = vim.trim(icons.ft.Markdown),
                    name = "Rmd",
                },
                zip = {
                    color = "#e84d31",
                    cterm_color = "166",
                    icon = vim.trim(icons.ft.Zip),
                    name = "Zip",
                },
                gz = {
                    color = "#e84d31",
                    cterm_color = "166",
                    icon = vim.trim(icons.ft.Zip),
                    name = "gz",
                },
                ["7z"] = {
                    color = "#e84d31",
                    cterm_color = "166",
                    icon = vim.trim(icons.ft.Zip),
                    name = "7z",
                },
                rar = {
                    color = "#e84d31",
                    cterm_color = "166",
                    icon = vim.trim(icons.ft.Zip),
                    name = "Zip",
                },
                theme = {
                    color = "#7c9fd5",
                    cterm_color = "39",
                    icon = vim.trim(icons.ft.Theme),
                    name = "Theme",
                },
                colorscheme = {
                    color = "#7c9fd5",
                    cterm_color = "39",
                    icon = vim.trim(icons.ft.Theme),
                    name = "ColorScheme",
                },
                profile = {
                    color = "#6d8086",
                    cterm_color = "66",
                    icon = vim.trim(icons.ft.Config),
                    name = "Profile",
                },
                rc = {
                    color = "#6d8086",
                    cterm_color = "66",
                    icon = vim.trim(icons.ft.Config),
                    name = "Rc",
                },
                jar = {
                    color = "#cc3e44",
                    cterm_color = "167",
                    icon = vim.trim(icons.ft.Java),
                    name = "Jar",
                },
                mp4 = {
                    color = "#FD971F",
                    cterm_color = "208",
                    icon = vim.trim(icons.ft.Video),
                    name = "Mp4",
                },
                mov = {
                    color = "#FD971F",
                    cterm_color = "208",
                    icon = vim.trim(icons.ft.Video),
                    name = "MOV",
                },
                avi = {
                    color = "#fd6c40",
                    cterm_color = "208",
                    icon = vim.trim(icons.ft.Video),
                    name = "AVI",
                },
                ipynb = {
                    color = "#f27726",
                    cterm_color = "166",
                    icon = vim.trim(icons.ft.Ipynb),
                    name = "Ipynb",
                },
                sh = {
                    color = "#89e051",
                    cterm_color = "113",
                    icon = vim.trim(icons.ft.Sh),
                    name = "Sh",
                },
                rs = {
                    -- color = "#dea584",
                    color = "#e43a25",
                    cterm_color = "216",
                    icon = vim.trim(icons.ft.Rust),
                    name = "Rs",
                },
                toml = {
                    color = "#6d8086",
                    cterm_color = "66",
                    icon = vim.trim(icons.ft.Config),
                    name = "Toml",
                },
                yaml = { color = "#e8274b", icon = vim.trim(icons.ft.Config), name = "Yaml" },
                yml = { color = "#e8274b", icon = vim.trim(icons.ft.Config), name = "Yml" },
                fish = { color = "#73a3b7", icon = vim.trim(icons.ft.Fish), name = "Fish" },
                gql = { color = "#e00097", icon = vim.trim(icons.ft.GraphQL), name = "GraphQL" },
                graphql = { color = "#e00097", icon = vim.trim(icons.ft.GraphQL), name = "GraphQL" },
                tf = { color = "#5F43E9", icon = vim.trim(icons.ft.Terraform), name = "Terraform" },
                env = { color = "#d0bf41", icon = vim.trim(icons.ft.Env), name = "Env" },
            },
            override_by_filename = {
                run_datasets = {
                    color = "#65767a",
                    cterm_color = "238",
                    icon = vim.trim(icons.ft.Sh),
                    name = "ShellRunDatasets",
                },
                configure = {
                    color = "#6d8086",
                    cterm_color = "66",
                    icon = vim.trim(icons.ft.Config),
                    name = "Configure",
                },
                ["package.json"] = {
                    color = "#bbbbbb",
                    cterm_color = "250",
                    icon = vim.trim(icons.ft.Nodejs),
                    name = "PackageJson",
                },
                ["package-lock.json"] = {
                    color = "#bbbbbb",
                    cterm_color = "250",
                    icon = vim.trim(icons.ft.Lock),
                    name = "PackageLockJson",
                },
                ["node_modules"] = { color = "#ea6962", icon = vim.trim(icons.ft.NodeModules), name = "NodeModules" },
                [".luacheckrc"] = {
                    color = "#6d8086",
                    cterm_color = "66",
                    icon = vim.trim(icons.ft.Config),
                    name = "LuaCheckRc",
                },
                [".gitattributes"] = {
                    color = "#e84d31",
                    cterm_color = "239",
                    icon = vim.trim(icons.ft.Git),
                    name = "GitAttributes",
                },
                [".gitconfig"] = {
                    color = "#e84d31",
                    cterm_color = "239",
                    icon = vim.trim(icons.ft.Git),
                    name = "GitConfig",
                },
                [".gitignore"] = {
                    color = "#e84d31",
                    cterm_color = "239",
                    icon = vim.trim(icons.ft.Git),
                    name = "GitIgnore",
                },
                [".gitmodules"] = {
                    color = "#e84d31",
                    cterm_color = "239",
                    icon = vim.trim(icons.ft.Git),
                    name = "GitModules",
                },
                ["README"] = {
                    color = "#6fb5ca",
                    cterm_color = "74",
                    icon = vim.trim(icons.ft.Markdown),
                    name = "Readme",
                },
                [".bash_profile"] = {
                    color = "#89e051",
                    cterm_color = "113",
                    icon = vim.trim(icons.ft.Config),
                    name = "BashProfile",
                },
                [".bashrc"] = {
                    color = "#89e051",
                    cterm_color = "113",
                    icon = vim.trim(icons.ft.Config),
                    name = "Bashrc",
                },
                ["LICENSE"] = { color = "#d8a657", icon = vim.trim(icons.ft.License), name = "License" },
                [".envrc"] = { color = "#d0bf41", icon = vim.trim(icons.ft.Env), name = "Envrc" },
                ["go.mod"] = { icon = vim.trim(icons.ft.Go), color = "#73a3b7", name = "GoMod" },
                ["go.sum"] = { icon = vim.trim(icons.ft.Go), color = "#73a3b7", name = "GoSum" },
                ["Cargo.toml"] = { color = "#d28446", icon = vim.trim(icons.ft.Rust), name = "CargoToml" }, -- doesn't work
                ["Cargo.lock"] = { color = "#d28446", icon = vim.trim(icons.ft.Rust), name = "CargoLock" }, -- doesn't work
            },
        },
    },
}