theme = "gruvbox_dark_hard"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
rulers = [120]

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[editor.statusline]
right = ["diagnostics", "selections", "position", "file-type"]

[editor.lsp]
display-inlay-hints = true

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "󰌒"
newline = "󰌑"
tabpad = "·"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
";" = "repeat_last_motion"
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]
D = [
  "extend_to_line_end",
  "yank_main_selection_to_clipboard",
  "delete_selection",
]
X = "extend_line_above"
