theme = "gruvbox_dark_hard"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
completion-trigger-len = 1
rulers = [120]

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[editor.lsp]
display-inlay-hints = true

# [editor.statusline]
# right = ["diagnostics", "selections", "position", "file-type"]

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "󰌒"
newline = "󰌑"
tabpad = "·"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
";" = "repeat_last_motion"
X = "extend_line_above"
C-d = ["half_page_down", "goto_window_center"]
C-u = ["half_page_up", "goto_window_center"]
# If you find having text remain selected while you have switched to insert or append mode
i = ["insert_mode", "collapse_selection"]
a = ["append_mode", "collapse_selection"]
# Scroll line up and down
C-n = ["move_line_down", "scroll_down"]
C-p = ["move_line_up", "scroll_up"]
# Move line up and down
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]

[keys.select]
X = "extend_line_above"

[keys.normal.space]
q = ":quit-all"
x = ":buffer-close"
"/" = { "/" = ":pipe-to zellij run --direction down --close-on-exit -- helix-live-grep", g = "global_search" }
